/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lp/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_api_lp_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /**
             * Source
             * @description LP problem text (DSL)
             */
            source: string;
            /**
             * Tableau Mode
             * @description Tableau pedagogy: auto (default paths), primal two-phase, dual simplex, or big-M.
             * @default auto
             * @enum {string}
             */
            tableau_mode: "auto" | "primal" | "dual" | "big_m";
            /**
             * Use Blands Rule
             * @description Use Bland’s rule for entering/leaving ties (primal/dual).
             * @default false
             */
            use_blands_rule: boolean;
            /**
             * Big M Value
             * @description Override M for big_m mode; when null, a scale-aware default is chosen.
             */
            big_m_value?: number | null;
        };
        /** AnalyzeResponse */
        AnalyzeResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Error Code
             * @description Stable machine-readable error code when ok=false.
             */
            error_code?: string | null;
            /**
             * Error Hint
             * @description Optional actionable hint for end users when ok=false.
             */
            error_hint?: string | null;
            /**
             * Error Context
             * @description Optional structured context for debugging or UI affordances.
             */
            error_context?: {
                [key: string]: unknown;
            } | null;
            /** Modeling Notes */
            modeling_notes?: string[];
            problem?: components["schemas"]["ParsedProblemView"] | null;
            /** Solve Status */
            solve_status?: ("optimal" | "infeasible" | "unbounded" | "not_attempted") | null;
            /** Optimal Value */
            optimal_value?: number | null;
            /** Optimal Point */
            optimal_point?: {
                [key: string]: number;
            } | null;
            /**
             * Constraints 2D
             * @default []
             */
            constraints_2d: components["schemas"]["ConstraintPlot2D"][];
            /** Feasible Region */
            feasible_region?: components["schemas"]["FeasibleRegion1D"] | components["schemas"]["FeasibleRegion2D"] | {
                [key: string]: unknown;
            } | null;
            /** Geometry Note */
            geometry_note?: string | null;
            /**
             * Tutor Steps
             * @default []
             */
            tutor_steps: components["schemas"]["TutorStep"][];
            tableau_walkthrough?: components["schemas"]["TableauWalkthrough"] | null;
            /**
             * Tableau Status
             * @default skipped
             * @enum {string}
             */
            tableau_status: "ok" | "not_supported_yet" | "skipped";
            /** Tableau Message */
            tableau_message?: string | null;
            /**
             * Tableau Verified
             * @description When a tableau walkthrough is returned, True if the final BFS matches HiGHS objective and primal feasibility within tolerance.
             */
            tableau_verified?: boolean | null;
            /**
             * Tableau Verify Message
             * @description Set when verification fails, or an informational note (e.g. non-unique optimum).
             */
            tableau_verify_message?: string | null;
        };
        /** ConstraintPlot2D */
        ConstraintPlot2D: {
            /** A */
            a: number;
            /** B */
            b: number;
            /** Rhs */
            rhs: number;
            /**
             * Sense
             * @enum {string}
             */
            sense: "<=" | ">=" | "=";
            /** Label */
            label: string;
        };
        /** FeasibleRegion1D */
        FeasibleRegion1D: {
            /**
             * Kind
             * @default interval_1d
             * @constant
             */
            kind: "interval_1d";
            /** Var */
            var: string;
            /** Lo */
            lo?: number | null;
            /** Hi */
            hi?: number | null;
        };
        /** FeasibleRegion2D */
        FeasibleRegion2D: {
            /**
             * Kind
             * @default polygon_2d
             * @constant
             */
            kind: "polygon_2d";
            /** Vertices */
            vertices: [
                number,
                number
            ][];
            /**
             * Clipped To Box
             * @default false
             */
            clipped_to_box: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ParsedProblemView */
        ParsedProblemView: {
            /**
             * Sense
             * @enum {string}
             */
            sense: "maximize" | "minimize";
            /** Variables */
            variables: string[];
            /** Objective */
            objective: {
                [key: string]: number;
            };
            /** Constraint Labels */
            constraint_labels: string[];
        };
        /** TableauStep */
        TableauStep: {
            /** Index */
            index: number;
            /** Tableau */
            tableau: number[][];
            /** Column Labels */
            column_labels: string[];
            /** Basis Labels */
            basis_labels: string[];
            /** Entering Col */
            entering_col?: number | null;
            /** Leaving Row */
            leaving_row?: number | null;
            /** Ratios */
            ratios?: (number | null)[] | null;
            /** Narrative */
            narrative: string;
        };
        /** TableauWalkthrough */
        TableauWalkthrough: {
            /**
             * Sense For Tableau
             * @enum {string}
             */
            sense_for_tableau: "maximize" | "minimize";
            /** Initial Narrative */
            initial_narrative: string;
            /** Steps */
            steps: components["schemas"]["TableauStep"][];
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "optimal" | "unbounded" | "infeasible" | "max_iterations";
        };
        /** TutorStep */
        TutorStep: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Detail */
            detail: string;
            /** Highlight Vertex Index */
            highlight_vertex_index?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    analyze_api_lp_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
